use_frameworks!

target 'SwiftChess_Example' do
  pod 'SwiftChess', :path => '../'

 # target 'SwiftChess_Tests' do
  #  inherit! :search_paths

    
  #end
end

target 'SwiftChess_Tests' do
  pod 'SwiftChess', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

